# frozen_string_literal: true

# This file was generated by the release workflow
# https://github.com/roshangautam/macos-tools/actions

class MacosTools < Formula
  desc "A collection of useful command-line utilities for macOS system management and maintenance"
  homepage "https://github.com/roshangautam/macos-tools"
  url "https://github.com/roshangautam/macos-tools/archive/refs/tags/v0.0.1.tar.gz"
  sha256 "0c37cc16b8ac3bda310d9c7d91374017f7428afc15dc4bd28b2262af2e115ae4"
  license "MIT"

  depends_on :macos
  depends_on "python@3.12"

  def install
    # Install Python package
    system "python3", "-m", "pip", "install", "--prefix=#{libexec}", "."

    # Create wrapper scripts
    bin.install_symlink #{libexec}/"bin/macos-tools"
  end

  test do
    system bin/"macos-tools", "--version"
  end
end
