#!/usr/bin/env ruby
# frozen_string_literal: true

# This script updates the Homebrew formula with the new version and SHA256

require 'erb'

class HomebrewFormula
  TEMPLATE = <<~FORMULA
    # frozen_string_literal: true
    
    # This file was generated by the release workflow
    # https://github.com/roshangautam/macos-tools/actions
    
    class MacosTools < Formula
      desc "A collection of useful command-line utilities for macOS system management and maintenance"
      homepage "https://github.com/roshangautam/macos-tools"
      url "<%= @tarball_url %>"
      sha256 "<%= @sha256 %>"
      license "MIT"
    
      depends_on :macos
      depends_on "python@3.12"
    
      def install
        # Install Python package
        system "python3", "-m", "pip", "install", "--prefix=#{libexec}", "."
        
        # Create wrapper scripts
        bin.install_symlink libexec/"bin/macos-tools"
      end
    
      test do
        system bin/"macos-tools", "--version"
      end
    end
  FORMULA

  def render(version, sha256)
    @tarball_url = "https://github.com/roshangautam/macos-tools/archive/refs/tags/v#{version}.tar.gz"
    @sha256 = sha256
    ERB.new(TEMPLATE, trim_mode: "-").result(binding)
  end
end

if ARGV.length != 2
  puts "Usage: #{$PROGRAM_NAME} <version> <sha256>"
  exit 1
end

version = ARGV[0]
sha256 = ARGV[1]

formula = HomebrewFormula.new.render(version, sha256)
puts formula
