name: Publish to Homebrew Tap

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    
    - name: Get version
      id: get_version
      run: |
        VERSION=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//')
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
    
    - name: Create source distribution
      run: |
        python setup.py sdist
    
    - name: Calculate SHA256
      id: sha256
      run: |
        SHA256=$(sha256sum dist/*.tar.gz | awk '{print $1}')
        echo "sha256=${SHA256}" >> $GITHUB_OUTPUT
    
    - name: Generate Homebrew formula
      run: |
        mkdir -p homebrew-tap/Formula
        ruby scripts/update_homebrew_formula.rb "${{ steps.get_version.outputs.version }}" "${{ steps.sha256.outputs.sha256 }}" > homebrew-tap/Formula/macos-tools.rb
        
        # Create a simple README if it doesn't exist
        if [ ! -f "homebrew-tap/README.md" ]; then
          echo "# macOS Tools Homebrew Tap" > homebrew-tap/README.md
          echo "\nTap this repository:\n\n\`\`\`bash\nbrew tap roshangautam/macos-tools https://github.com/roshangautam/macos-tools.git\n\`\`\`" >> homebrew-tap/README.md
        fi
